name: xayn_readability
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none
homepage: https://www.xayn.com

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.8.5+1
  html: ^0.15.0
  http_client: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.4
