name: xayn_readability
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none
homepage: https://www.xayn.com

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  flutter_widget_from_html: ^0.14.9
  html: ^0.15.4
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
